version: "2"
services:
  zeo:
    image: plone:5.1.4
    labels:
      io.rancher.scheduler.affinity:host_label: db=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    volumes:
    - zeo:/data
    command: ["zeo"]

  plone:
    image: avoinea/plone-demo:1.4
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    links:
    - zeo:zeo
    environment:
      ZEO_ADDRESS: zeo:8080

  lb:
    image: eeacms/haproxy:1.7-4.0
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    links:
    - plone:plone
    ports:
    - "8080"
    - "1936"
    environment:
      FRONTEND_PORT: "8080"
      BACKENDS_PORT: "8080"
      BACKENDS: "plone"
      DNS_ENABLED: "true"

volumes:
  zeo:
